In [285]:
import pandas as pd
import warnings 
warnings.filterwarnings(action='ignore')

In [286]:
tabla = pd.read_csv("attacks.csv", encoding ="latin1")
tabla.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [287]:
tabla.shape

(25723, 24)

In [288]:
tabla.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [289]:
tabla_clean = tabla.drop(columns= ['Unnamed: 22', 'Unnamed: 23','href formula'])
total_rows=tabla_clean.pdf.shape[0]
total_rows

25723

In [290]:
tabla_clean[['Date', 'Location', 'Name']].head()

          Date                        Location             Name
0  25-Jun-2018     Oceanside, San Diego County      Julie Wolfe
1  18-Jun-2018  St. Simon Island, Glynn County  Adyson McNeely
2  09-Jun-2018                    Habush, Oahu      John Denges
3  08-Jun-2018              Arrawarra Headland             male
4  04-Jun-2018                        La Ticla   Gustavo Ramos

In [291]:
tabla_clean.Year.value_counts(sort='ascending')

2015.0    143
2017.0    136
2016.0    130
2011.0    128
2014.0    127
         ...
1753.0      1
77.0        1
1785.0      1
1580.0      1
1543.0      1
Name: Year, Length: 249, dtype: int64

In [292]:
print (tabla.columns.shape)
print (tabla_clean.columns.shape)
print (type(tabla_clean.columns.shape))

(24,)
(21,)
<class 'tuple'>

In [293]:
null_cols=tabla_clean.isnull().sum()
null_cols[null_cols>0]

Case Number               17021
Date                      19421
Year                      19423
Type                      19425
Country                   19471
Area                      19876
Location                  19961
Activity                  19965
Name                      19631
Sex                       19986
Age                       22252
Injury                    19449
Fatal (Y/N)               19960
Time                      22775
Species                   22259
Investigator or Source    19438
pdf                       19421
href                      19421
Case Number.1             19421
Case Number.2             19421
original order            19414
dtype: int64

In [294]:
bad_index=list(tabla_clean.Injury[tabla_clean.Injury.isnull()].index)
bad_index[0:20]

[1270,
 1366,
 2250,
 2267,
 2648,
 3038,
 3207,
 3298,
 3434,
 3457,
 3491,
 3712,
 3838,
 3841,
 4060,
 4517,
 4976,
 5370,
 5547,
 5965]

In [295]:
tabla_clean.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href', 'Case Number.1',
       'Case Number.2', 'original order'],
      dtype='object')

In [296]:
lcol = tabla_clean.rename(columns={'Sex ': 'Sex', 'Case Number.1': 'Case 1', 'Case Number.2': 'Case 2', 'Investigator or Source': 'Source', 'href': 'Link'})

In [297]:
lcol.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Source', 'pdf', 'Link', 'Case 1', 'Case 2',
       'original order'],
      dtype='object')

In [298]:
lcol.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Injury,Fatal (Y/N),Time,Species,Source,pdf,Link,Case 1,Case 2,original order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0

In [299]:
print(lcol.isnull())

       Case Number   Date   Year   Type  Country   Area  Location  Activity  \
0            False  False  False  False    False  False     False     False
1            False  False  False  False    False  False     False     False
2            False  False  False  False    False  False     False     False
3            False  False  False  False    False  False     False     False
4            False  False  False  False    False  False     False     False
...            ...    ...    ...    ...      ...    ...       ...       ...
25718         True   True   True   True     True   True      True      True
25719         True   True   True   True     True   True      True      True
25720         True   True   True   True     True   True      True      True
25721         True   True   True   True     True   True      True      True
25722        False   True   True   True     True   True      True      True

        Name    Sex  ...  Injury  Fatal (Y/N)   Time  Species   Source    pdf  \
0      False  False  ...   False        False  False     False   False  False
1      False  False  ...   False        False  False      True   False  False
2      False  False  ...   False        False  False      True   False  False
3      False  False  ...   False        False   True     False   False  False
4      False  False  ...   False        False   True     False   False  False
...      ...    ...  ...     ...          ...    ...       ...     ...    ...
25718   True   True  ...    True         True   True      True    True   True
25719   True   True  ...    True         True   True      True    True   True
25720   True   True  ...    True         True   True      True    True   True
25721   True   True  ...    True         True   True      True    True   True
25722   True   True  ...    True         True   True      True    True   True

        Link  Case 1  Case 2  original order
0      False   False   False           False
1      False   False   False           False
2      False   False   False           False
3      False   False   False           False
4      False   False   False           False
...      ...     ...     ...             ...
25718   True    True    True            True
25719   True    True    True            True
25720   True    True    True            True
25721   True    True    True            True
25722   True    True    True            True

[25723 rows x 21 columns]

In [301]:
tabla_clean = tabla_clean.fillna('no info') 
tabla_clean

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href,Case Number.1,Case Number.2,original order
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,Minor injury to left thigh,N,14h00 -15h00,no info,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,Injury to left lower leg from surfboard skeg,N,07h45,no info,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,Minor injury to lower leg,N,no info,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300
4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,Lacerations to leg & hand shark PROVOKED INCIDENT,N,no info,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,no info,no info,no info,no info,no info,no info,no info,no info,no info,no info,...,no info,no info,no info,no info,no info,no info,no info,no info,no info,no info
25719,no info,no info,no info,no info,no info,no info,no info,no info,no info,no info,...,no info,no info,no info,no info,no info,no info,no info,no info,no info,no info
25720,no info,no info,no info,no info,no info,no info,no info,no info,no info,no info,...,no info,no info,no info,no info,no info,no info,no info,no info,no info,no info
25721,no info,no info,no info,no info,no info,no info,no info,no info,no info,no info,...,no info,no info,no info,no info,no info,no info,no info,no info,no info,no info
25722,xx,no info,no info,no info,no info,no info,no info,no info,no info,no info,...,no info,no info,no info,no info,no info,no info,no info,no info,no info,no info