In [197]:
!pip3 install tweety
from bs4 import BeautifulSoup as bs
import requests
import pandas as pd
import re
import json
import http.client

Collecting tweety
  Using cached https://files.pythonhosted.org/packages/0c/b8/1aaac0db3ce8a58234d5d02c76ebc5768250a22f8556b547279e0860f9b5/tweety-0.1.6.tar.gz
Requirement already satisfied: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from tweety) (4.8.1)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from tweety) (0.25.2)
Requirement already satisfied: selenium in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from tweety) (3.141.0)
Requirement already satisfied: spacy in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from tweety) (2.2.2)
Requirement already satisfied: vaderSentiment in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from tweety) (3.2.1)
Requirement already satisfied: textblob in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from tweety) (0.15.3)
Collecting chromedriver-binary==74.0.3729.6.0
  Using cached https://files.pythonhosted.org/packages/2f/e5/f699539293a65a57249744a1d60c8671c21d21019c01291313cafe81ae6d/chromedriver-binary-74.0.3729.6.0.tar.gz
Requirement already satisfied: soupsieve>=1.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from beautifulsoup4->tweety) (1.9.5)
Requirement already satisfied: pytz>=2017.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas->tweety) (2019.3)
Requirement already satisfied: numpy>=1.13.3 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas->tweety) (1.17.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas->tweety) (2.8.0)
Requirement already satisfied: urllib3 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from selenium->tweety) (1.25.6)
Requirement already satisfied: importlib-metadata>=0.20; python_version < "3.8" in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from spacy->tweety) (0.23)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from spacy->tweety) (40.8.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from spacy->tweety) (2.22.0)
Requirement already satisfied: blis<0.5.0,>=0.4.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from spacy->tweety) (0.4.1)
Requirement already satisfied: srsly<1.1.0,>=0.1.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from spacy->tweety) (0.2.0)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from spacy->tweety) (1.0.2)
Requirement already satisfied: plac<1.2.0,>=0.9.6 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from spacy->tweety) (1.1.3)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from spacy->tweety) (2.0.3)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from spacy->tweety) (3.0.2)
Requirement already satisfied: wasabi<1.1.0,>=0.3.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from spacy->tweety) (0.4.0)
Requirement already satisfied: thinc<7.4.0,>=7.3.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from spacy->tweety) (7.3.1)
Requirement already satisfied: nltk>=3.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from textblob->tweety) (3.4.5)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas->tweety) (1.12.0)
Requirement already satisfied: zipp>=0.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from importlib-metadata>=0.20; python_version < "3.8"->spacy->tweety) (0.6.0)
Requirement already satisfied: idna<2.9,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests<3.0.0,>=2.13.0->spacy->tweety) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests<3.0.0,>=2.13.0->spacy->tweety) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests<3.0.0,>=2.13.0->spacy->tweety) (2019.9.11)
Requirement already satisfied: tqdm<5.0.0,>=4.10.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from thinc<7.4.0,>=7.3.0->spacy->tweety) (4.38.0)
Requirement already satisfied: more-itertools in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from zipp>=0.5->importlib-metadata>=0.20; python_version < "3.8"->spacy->tweety) (7.2.0)
Installing collected packages: chromedriver-binary, tweety
    Running setup.py install for chromedriver-binary ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/qr/696m7ns50h596hq6018zgdqr0000gn/T/pip-install-r68e2hoa/chromedriver-binary/setup.py'"'"'; __file__='"'"'/private/var/folders/qr/696m7ns50h596hq6018zgdqr0000gn/T/pip-install-r68e2hoa/chromedriver-binary/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/qr/696m7ns50h596hq6018zgdqr0000gn/T/pip-record-w97nom9x/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/qr/696m7ns50h596hq6018zgdqr0000gn/T/pip-install-r68e2hoa/chromedriver-binary/
    Complete output (79 lines):
    running install
    running build
    running build_py

    Downloading Chromedriver...

    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
        encode_chunked=req.has_header('Transfer-encoding'))
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1244, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1290, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1239, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1026, in _send_output
        self.send(msg)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 966, in send
        self.connect()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1414, in connect
        server_hostname=server_hostname)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
        session=session
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
        self.do_handshake()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/private/var/folders/qr/696m7ns50h596hq6018zgdqr0000gn/T/pip-install-r68e2hoa/chromedriver-binary/setup.py", line 43, in run
        response = urlopen(url)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
        response = self._open(req, data)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
        '_open', req)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
        result = func(*args)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qr/696m7ns50h596hq6018zgdqr0000gn/T/pip-install-r68e2hoa/chromedriver-binary/setup.py", line 83, in <module>
        cmdclass={'build_py': DownloadChromedriver}
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/qr/696m7ns50h596hq6018zgdqr0000gn/T/pip-install-r68e2hoa/chromedriver-binary/setup.py", line 47, in run
        raise RuntimeError('Failed to download chromedriver archive: {}'.format(url))
    RuntimeError: Failed to download chromedriver archive: https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_mac64.zip
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/qr/696m7ns50h596hq6018zgdqr0000gn/T/pip-install-r68e2hoa/chromedriver-binary/setup.py'"'"'; __file__='"'"'/private/var/folders/qr/696m7ns50h596hq6018zgdqr0000gn/T/pip-install-r68e2hoa/chromedriver-binary/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/qr/696m7ns50h596hq6018zgdqr0000gn/T/pip-record-w97nom9x/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

In [198]:
url = 'https://es.wikipedia.org/wiki/Fortune_Global_500'
html=requests.get(url).content
soup = bs(html,"html.parser")
table =soup.find_all('table')
good=table[-2]
good

<table class="wikitable sortable">
<tbody><tr>
<th>Rango</th>
<th>Ciudad</th>
<th>País</th>
<th>Número de compañías Global 500<br/></th>
<th>Ingresos ($millones)<br/>
</th></tr>
<tr>
<td align="center">1</td>
<td><a href="/wiki/Tokio" title="Tokio">Tokio</a></td>
<td><span class="flagicon"><img alt="Bandera de Japón" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="13" src="//upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/20px-Flag_of_Japan.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/30px-Flag_of_Japan.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/40px-Flag_of_Japan.svg.png 2x" title="Bandera de Japón" width="20"/> </span><a href="/wiki/Jap%C3%B3n" title="Japón">Japón</a></td>
<td align="center">51</td>
<td align="center">2,237,560
</td></tr>
<tr>
<td align="center">2</td>
<td><a href="/wiki/Par%C3%ADs" title="París">París</a></td>
<td><span class="flagicon"><img alt="Bandera de Francia" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="13" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/20px-Flag_of_France.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/30px-Flag_of_France.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/40px-Flag_of_France.svg.png 2x" title="Bandera de Francia" width="20"/> </span><a href="/wiki/Francia" title="Francia">Francia</a></td>
<td align="center">27</td>
<td align="center">1,399,172
</td></tr>
<tr>
<td align="center">3</td>
<td><a href="/wiki/Pek%C3%ADn" title="Pekín">Pekín</a></td>
<td><span class="flagicon"><img alt="Bandera de la República Popular China" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="13" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/20px-Flag_of_the_People%27s_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/30px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/40px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" title="Bandera de la República Popular China" width="20"/> </span><a href="/wiki/Rep%C3%BAblica_Popular_China" title="República Popular China">China</a></td>
<td align="center">26</td>
<td align="center">1,361,407
</td></tr>
<tr>
<td align="center">4</td>
<td><a href="/wiki/Nueva_York" title="Nueva York">Nueva York</a></td>
<td><span class="flagicon"><img alt="Bandera de Estados Unidos" class="thumbborder" data-file-height="650" data-file-width="1235" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/20px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/30px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/40px-Flag_of_the_United_States.svg.png 2x" title="Bandera de Estados Unidos" width="20"/> </span><a href="/wiki/Estados_Unidos" title="Estados Unidos">Estados Unidos</a></td>
<td align="center">18</td>
<td align="center">869,150
</td></tr>
<tr>
<td align="center">5</td>
<td><a href="/wiki/Londres" title="Londres">Londres</a></td>
<td><span class="flagicon"><img alt="Bandera de Reino Unido" class="thumbborder" data-file-height="600" data-file-width="1200" decoding="async" height="10" src="//upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Flag_of_the_United_Kingdom.svg/20px-Flag_of_the_United_Kingdom.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Flag_of_the_United_Kingdom.svg/30px-Flag_of_the_United_Kingdom.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Flag_of_the_United_Kingdom.svg/40px-Flag_of_the_United_Kingdom.svg.png 2x" title="Bandera de Reino Unido" width="20"/> </span><a href="/wiki/Reino_Unido" title="Reino Unido">Reino Unido</a></td>
<td align="center">15</td>
<td align="center">994,772
</td></tr>
<tr>
<td align="center">6</td>
<td><a href="/wiki/Se%C3%BAl" title="Seúl">Seúl</a></td>
<td><span class="flagicon"><img alt="Bandera de Corea del Sur" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="13" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/20px-Flag_of_South_Korea.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/30px-Flag_of_South_Korea.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/40px-Flag_of_South_Korea.svg.png 2x" title="Bandera de Corea del Sur" width="20"/> </span><a href="/wiki/Corea_del_Sur" title="Corea del Sur">Corea del Sur</a></td>
<td align="center">11</td>
<td align="center">519,351
</td></tr>
<tr>
<td align="center">7</td>
<td><a href="/wiki/Madrid" title="Madrid">Madrid</a></td>
<td><span class="flagicon"><img alt="Bandera de España" class="thumbborder" data-file-height="500" data-file-width="750" decoding="async" height="13" src="//upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/20px-Flag_of_Spain.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/30px-Flag_of_Spain.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/40px-Flag_of_Spain.svg.png 2x" title="Bandera de España" width="20"/> </span><a href="/wiki/Espa%C3%B1a" title="España">España</a></td>
<td align="center">9</td>
<td align="center">434,393
</td></tr>
<tr>
<td align="center">8</td>
<td><a href="/wiki/Toronto" title="Toronto">Toronto</a></td>
<td><span class="flagicon"><img alt="Bandera de Canadá" class="thumbborder" data-file-height="600" data-file-width="1200" decoding="async" height="10" src="//upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/20px-Flag_of_Canada_%28Pantone%29.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/30px-Flag_of_Canada_%28Pantone%29.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/40px-Flag_of_Canada_%28Pantone%29.svg.png 2x" title="Bandera de Canadá" width="20"/> </span><a href="/wiki/Canad%C3%A1" title="Canadá">Canadá</a></td>
<td align="center">7</td>
<td align="center">195,510
</td></tr>
<tr>
<td align="center">8</td>
<td><a class="mw-redirect" href="/wiki/Z%C3%BCrich" title="Zürich">Zürich</a></td>
<td><span class="flagicon"><img alt="Bandera de Suiza" class="thumbborder" data-file-height="512" data-file-width="512" decoding="async" height="20" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/20px-Flag_of_Switzerland.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/30px-Flag_of_Switzerland.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/40px-Flag_of_Switzerland.svg.png 2x" title="Bandera de Suiza" width="20"/> </span><a href="/wiki/Suiza" title="Suiza">Suiza</a></td>
<td align="center">7</td>
<td align="center">242,595
</td></tr>
<tr>
<td align="center">8</td>
<td><a href="/wiki/Osaka" title="Osaka">Osaka</a></td>
<td><span class="flagicon"><img alt="Bandera de Japón" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="13" src="//upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/20px-Flag_of_Japan.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/30px-Flag_of_Japan.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/40px-Flag_of_Japan.svg.png 2x" title="Bandera de Japón" width="20"/> </span><a href="/wiki/Jap%C3%B3n" title="Japón">Japón</a></td>
<td align="center">7</td>
<td align="center">291,492
</td></tr>
<tr>
<td align="center">8</td>
<td><a href="/wiki/Mosc%C3%BA" title="Moscú">Moscú</a></td>
<td><span class="flagicon"><img alt="Bandera de Rusia" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="13" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/20px-Flag_of_Russia.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/30px-Flag_of_Russia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/40px-Flag_of_Russia.svg.png 2x" title="Bandera de Rusia" width="20"/> </span><a href="/wiki/Rusia" title="Rusia">Rusia</a></td>
<td align="center">7</td>
<td align="center">380,530
</td></tr>
<tr>
<td align="center">8</td>
<td><a href="/wiki/M%C3%BAnich" title="Múnich">Múnich</a></td>
<td><span class="flagicon"><img alt="Bandera de Alemania" class="thumbborder" data-file-height="600" data-file-width="1000" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/20px-Flag_of_Germany.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/30px-Flag_of_Germany.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/40px-Flag_of_Germany.svg.png 2x" title="Bandera de Alemania" width="20"/> </span><a href="/wiki/Alemania" title="Alemania">Alemania</a></td>
<td align="center">7</td>
<td align="center">485,386
</td></tr></tbody></table>

In [199]:
data=[]


for e in good.find_all('tr'):
    fila=[f for f in e.find_all('td')]
    if len(fila)>0:
        pais={'Ranking':str(fila[0].text),
              'Ciudad':fila[1].find('a').text.strip(),
              'Pais':fila[2].find('a').text.strip(),
              'Global companies':str(fila[3].text),
              'Ingreso':str(fila[4].text)}
        data.append(pais)
df=pd.DataFrame(data)

In [200]:
df

   Ranking      Ciudad            Pais Global companies      Ingreso
0        1       Tokio           Japón               51  2,237,560\n
1        2       París         Francia               27  1,399,172\n
2        3       Pekín           China               26  1,361,407\n
3        4  Nueva York  Estados Unidos               18    869,150\n
4        5     Londres     Reino Unido               15    994,772\n
5        6        Seúl   Corea del Sur               11    519,351\n
6        7      Madrid          España                9    434,393\n
7        8     Toronto          Canadá                7    195,510\n
8        8      Zürich           Suiza                7    242,595\n
9        8       Osaka           Japón                7    291,492\n
10       8       Moscú           Rusia                7    380,530\n
11       8      Múnich        Alemania                7    485,386\n

In [201]:
df.Ingreso = df.Ingreso.str.replace('\n', '')
df.Ingreso = df.Ingreso.str.replace(',', '')
df

   Ranking      Ciudad            Pais Global companies  Ingreso
0        1       Tokio           Japón               51  2237560
1        2       París         Francia               27  1399172
2        3       Pekín           China               26  1361407
3        4  Nueva York  Estados Unidos               18   869150
4        5     Londres     Reino Unido               15   994772
5        6        Seúl   Corea del Sur               11   519351
6        7      Madrid          España                9   434393
7        8     Toronto          Canadá                7   195510
8        8      Zürich           Suiza                7   242595
9        8       Osaka           Japón                7   291492
10       8       Moscú           Rusia                7   380530
11       8      Múnich        Alemania                7   485386

In [202]:
df['Ingreso'] = df['Ingreso'].apply(pd.to_numeric)
df['Global companies'] = df['Global companies'].apply(pd.to_numeric)
df['AvgRevenueXCompanie'] = df.Ingreso / df['Global companies']
df

,Ranking,Ciudad,Pais,Global companies,Ingreso,AvgRevenueXCompanie
0,1,Tokio,Japón,51,2237560,43873.725490
1,2,París,Francia,27,1399172,51821.185185
2,3,Pekín,China,26,1361407,52361.807692
3,4,Nueva York,Estados Unidos,18,869150,48286.111111
4,5,Londres,Reino Unido,15,994772,66318.133333
5,6,Seúl,Corea del Sur,11,519351,47213.727273
6,7,Madrid,España,9,434393,48265.888889
7,8,Toronto,Canadá,7,195510,27930.000000
8,8,Zürich,Suiza,7,242595,34656.428571
9,8,Osaka,Japón,7,291492,41641.714286
10,8,Moscú,Rusia,7,380530,54361.428571
11,8,Múnich,Alemania,7,485386,69340.857143

In [203]:
df.index = df.Ranking
df.drop(df.Ranking)
df
#Se puede observar el ingreso promedio de las compañias en el ranking 10 de las ciudades con mayor ingreso
#En la tabla se puede observar que a pesar de Muinch estar en el ranking 8, cada una de sus compañias tienen un ingreso promedio mayor que al de las demas, seguido de Londres que esta en el 5 lugar

,Ranking,Ciudad,Pais,Global companies,Ingreso,AvgRevenueXCompanie
Ranking,,,,,,
1,1,Tokio,Japón,51,2237560,43873.725490
2,2,París,Francia,27,1399172,51821.185185
3,3,Pekín,China,26,1361407,52361.807692
4,4,Nueva York,Estados Unidos,18,869150,48286.111111
5,5,Londres,Reino Unido,15,994772,66318.133333
6,6,Seúl,Corea del Sur,11,519351,47213.727273
7,7,Madrid,España,9,434393,48265.888889
8,8,Toronto,Canadá,7,195510,27930.000000
8,8,Zürich,Suiza,7,242595,34656.428571
8,8,Osaka,Japón,7,291492,41641.714286
8,8,Moscú,Rusia,7,380530,54361.428571
8,8,Múnich,Alemania,7,485386,69340.857143

In [374]:
df2 = pd.read_json('https://www.thecocktaildb.com/api/json/v1/1/filter.php?a=Alcoholic')
for e in df2.drinks:
    print(e)

{'strDrink': "'57 Chevy with a White License Plate", 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qyyvtu1468878544.jpg', 'idDrink': '14029'}
{'strDrink': '1-900-FUK-MEUP', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/uxywyw1468877224.jpg', 'idDrink': '15395'}
{'strDrink': '110 in the shade', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xxyywq1454511117.jpg', 'idDrink': '15423'}
{'strDrink': '151 Florida Bushwacker', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rvwrvv1468877323.jpg', 'idDrink': '14588'}
{'strDrink': '155 Belmont', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yqvvqs1475667388.jpg', 'idDrink': '15346'}
{'strDrink': '24k nightmare', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yyrwty1468877498.jpg', 'idDrink': '17060'}
{'strDrink': '252', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rtpxqw1468877562.jpg', 'idDrink': '15288'}
{'strDrink': '3 Wise Men', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wxqpyw1468877677.jpg', 'idDrink': '13899'}
{'strDrink': '3-Mile Long Island Iced Tea', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rrtssw1472668972.jpg', 'idDrink': '15300'}
{'strDrink': '410 Gone', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xtuyqv1472669026.jpg', 'idDrink': '13581'}
{'strDrink': '50/50', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wwpyvr1461919316.jpg', 'idDrink': '14598'}
{'strDrink': '501 Blue', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ywxwqs1461867097.jpg', 'idDrink': '17105'}
{'strDrink': '69 Special', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vqyxqx1472669095.jpg', 'idDrink': '13940'}
{'strDrink': '747', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xxsxqy1472668106.jpg', 'idDrink': '14229'}
{'strDrink': '747 Drink', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/8ozumt1572901761.jpg', 'idDrink': '178318'}
{'strDrink': '9 1/2 Weeks', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xvwusr1472669302.jpg', 'idDrink': '16108'}
{'strDrink': 'A Day at the Beach', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/trptts1454514474.jpg', 'idDrink': '15200'}
{'strDrink': 'A Furlong Too Late', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ssxvww1472669166.jpg', 'idDrink': '17831'}
{'strDrink': "A Gilligan's Island", 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wysqut1461867176.jpg', 'idDrink': '16943'}
{'strDrink': 'A midsummernight dream', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ysqvqp1461867292.jpg', 'idDrink': '15675'}
{'strDrink': 'A Night In Old Mandalay', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vyrvxt1461919380.jpg', 'idDrink': '17832'}
{'strDrink': 'A Piece of Ass', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/tqxyxx1472719737.jpg', 'idDrink': '16405'}
{'strDrink': 'A Splash of Nash', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rsvtrr1472668201.jpg', 'idDrink': '14564'}
{'strDrink': 'A True Amaretto Sour', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rptuxy1472669372.jpg', 'idDrink': '17005'}
{'strDrink': 'A. J.', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/uryyrr1472811418.jpg', 'idDrink': '17833'}
{'strDrink': 'A.D.M. (After Dinner Mint)', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ruxuvp1472669600.jpg', 'idDrink': '14560'}
{'strDrink': 'A1', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg', 'idDrink': '17222'}
{'strDrink': 'Abbey Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/quyyuw1472811568.jpg', 'idDrink': '17834'}
{'strDrink': 'Abbey Martini', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/2mcozt1504817403.jpg', 'idDrink': '17223'}
{'strDrink': 'ABC', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg', 'idDrink': '13501'}
{'strDrink': 'Abilene', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ysqwwt1461919465.jpg', 'idDrink': '17835'}
{'strDrink': 'Absinthe #2', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/uxxtrt1472667197.jpg', 'idDrink': '12790'}
{'strDrink': 'Absolut Evergreen', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wrxrxp1472812609.jpg', 'idDrink': '14374'}
{'strDrink': 'Absolut limousine', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ssqpyw1472719844.jpg', 'idDrink': '14372'}
{'strDrink': 'Absolut Sex', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xtrvtx1472668436.jpg', 'idDrink': '14360'}
{'strDrink': 'Absolut Stress #2', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xuyqrw1472811825.jpg', 'idDrink': '15597'}
{'strDrink': 'Absolut Summertime', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/trpxxs1472669662.jpg', 'idDrink': '14107'}
{'strDrink': 'Absolutely Cranberry Smash', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vqwstv1472811884.jpg', 'idDrink': '15024'}
{'strDrink': 'Absolutely Fabulous', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/abcpwr1504817734.jpg', 'idDrink': '17224'}
{'strDrink': 'Absolutly Screwed Up', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yvxrwv1472669728.jpg', 'idDrink': '16134'}
{'strDrink': 'Acapulco', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vtpsvr1472811976.jpg', 'idDrink': '17836'}
{'strDrink': 'Ace', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg', 'idDrink': '17225'}
{'strDrink': 'ACID', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xuxpxt1479209317.jpg', 'idDrink': '14610'}
{'strDrink': 'Adam', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rwuxsv1472812169.jpg', 'idDrink': '17837'}
{'strDrink': 'Adam & Eve', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vfeumw1504819077.jpg', 'idDrink': '17226'}
{'strDrink': 'Adam Bomb', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/tpxurs1454513016.jpg', 'idDrink': '16333'}
{'strDrink': 'Adam Sunrise', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vtuyvu1472812112.jpg', 'idDrink': '15567'}
{'strDrink': 'Addington', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ib0b7g1504818925.jpg', 'idDrink': '17227'}
{'strDrink': 'Addison', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yzva7x1504820300.jpg', 'idDrink': '17228'}
{'strDrink': 'Addison Special', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/4vo5651493068493.jpg', 'idDrink': '14272'}
{'strDrink': 'Adios Amigos Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/8nk2mp1504819893.jpg', 'idDrink': '17229'}
{'strDrink': 'Adonis Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xrvruq1472812030.jpg', 'idDrink': '17838'}
{'strDrink': 'Affair', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wxrsxx1472720734.jpg', 'idDrink': '17839'}
{'strDrink': 'Affinity', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/nwatpb1504817045.jpg', 'idDrink': '17840'}
{'strDrink': 'After Dinner Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vtytxq1483387578.jpg', 'idDrink': '11010'}
{'strDrink': 'After Five', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/sk3lr91493068595.jpg', 'idDrink': '13807'}
{'strDrink': 'After sex', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xrl66i1493068702.jpg', 'idDrink': '15182'}
{'strDrink': 'After Supper Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/quyxwu1483387610.jpg', 'idDrink': '11011'}
{'strDrink': 'Afternoon', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vyrurp1472667777.jpg', 'idDrink': '13162'}
{'strDrink': 'Alabama Slammer', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qtwxwr1483387647.jpg', 'idDrink': '11012'}
{'strDrink': 'Alaska Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wsyryt1483387720.jpg', 'idDrink': '11013'}
{'strDrink': 'Alexander', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/urystu1478253039.jpg', 'idDrink': '11014'}
{'strDrink': 'Alfie Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ypxsqy1483387829.jpg', 'idDrink': '11019'}
{'strDrink': 'Algonquin', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/uwryxx1483387873.jpg', 'idDrink': '11020'}
{'strDrink': 'Alice in Wonderland', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/g12lj41493069391.jpg', 'idDrink': '17094'}
{'strDrink': 'Allegheny', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/uwvyts1483387934.jpg', 'idDrink': '11021'}
{'strDrink': 'Allies Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qvprvp1483388104.jpg', 'idDrink': '11022'}
{'strDrink': 'Almeria', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rwsyyu1483388181.jpg', 'idDrink': '11023'}
{'strDrink': 'Almond Chocolate Coffee', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/jls02c1493069441.jpg', 'idDrink': '16082'}
{'strDrink': 'Almond Joy', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xutuqs1483388296.jpg', 'idDrink': '11024'}
{'strDrink': 'Amaretto And Cream', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/dj8n0r1504375018.jpg', 'idDrink': '11025'}
{'strDrink': 'Amaretto Liqueur', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/swqxuv1472719649.jpg', 'idDrink': '12792'}
{'strDrink': 'Amaretto Mist', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/utpxxq1483388370.jpg', 'idDrink': '11026'}
{'strDrink': 'Amaretto Rose', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/3jm41q1493069578.jpg', 'idDrink': '11027'}
{'strDrink': 'Amaretto Shake', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xk79al1493069655.jpg', 'idDrink': '15194'}
{'strDrink': 'Amaretto Sour', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xnzc541493070211.jpg', 'idDrink': '13731'}
{'strDrink': 'Amaretto Stinger', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vvop4w1493069934.jpg', 'idDrink': '11028'}
{'strDrink': 'Amaretto Stone Sour', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xwryyx1472719921.jpg', 'idDrink': '14306'}
{'strDrink': 'Amaretto Stone Sour #3', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wutxqr1472720012.jpg', 'idDrink': '16100'}
{'strDrink': 'Amaretto Sunrise', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/akcpsh1493070267.jpg', 'idDrink': '14578'}
{'strDrink': 'Amaretto Sunset', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/apictz1493069760.jpg', 'idDrink': '17168'}
{'strDrink': 'Amaretto Sweet & Sour', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vswwus1472668546.jpg', 'idDrink': '16202'}
{'strDrink': 'Amaretto Tea', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/b7qzo21493070167.jpg', 'idDrink': '11029'}
{'strDrink': 'Americano', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/trwruu1478253126.jpg', 'idDrink': '15941'}
{'strDrink': 'Angel Face', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vqpptp1478253178.jpg', 'idDrink': '11034'}
{'strDrink': 'Angelica Liqueur', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yuurps1472667672.jpg', 'idDrink': '12794'}
{'strDrink': 'Apple Grande', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wqrptx1472668622.jpg', 'idDrink': '16289'}
{'strDrink': 'Apple Pie with A Crust', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qspqxt1472720078.jpg', 'idDrink': '16958'}
{'strDrink': 'Apple Slammer', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/09yd5f1493069852.jpg', 'idDrink': '13683'}
{'strDrink': 'Applecar', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/sbffau1504389764.jpg', 'idDrink': '11046'}
{'strDrink': 'Applejack', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/sutyqp1479209062.jpg', 'idDrink': '16311'}
{'strDrink': 'Apricot Lady', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/146f251504389814.jpg', 'idDrink': '11050'}
{'strDrink': 'Apricot punch', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/tuxxtp1472668667.jpg', 'idDrink': '15849'}
{'strDrink': 'Aquamarine', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/zvsre31572902738.jpg', 'idDrink': '178319'}
{'strDrink': 'Archbishop', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xpqwrt1441207307.jpg', 'idDrink': '11052'}
{'strDrink': 'Arctic Fish', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ttsvwy1472668781.jpg', 'idDrink': '14622'}
{'strDrink': 'Arctic Mouthwash', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wqstwv1478963735.jpg', 'idDrink': '17118'}
{'strDrink': 'Arise My Love', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wyrrwv1441207432.jpg', 'idDrink': '11053'}
{'strDrink': 'Arizona Antifreeze', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/dbtylp1493067262.jpg', 'idDrink': '16354'}
{'strDrink': 'Arizona Stingers', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/y7w0721493068255.jpg', 'idDrink': '14584'}

In [375]:
columnas =[]
for items in df2.drinks:
    for key in items:
        if key not in columnas:
            columnas.append(key)

In [378]:
strDrink=[]
strDrinkThumb=[]
idDrink =[]
for item in df2.drinks:
    if item['strDrink'] not in strDrink:   
        strDrink.append(item['strDrink'])
    if item['strDrinkThumb'] not in strDrinkThumb:   
        strDrinkThumb.append(item['strDrinkThumb'])
    if item['idDrink'] not in idDrink:   
        idDrink.append(item['idDrink'])

In [385]:
len(idDrink)

100

In [400]:
data = {columnas[0]:strDrink, columnas[1]:strDrinkThumb, columnas[2]:idDrink}
newdf = pd.DataFrame(data)
newdf.rename(columns={'strDrink':'DrinkName', 'strDrinkThumb':'Link', 'idDrink':'IdDrink'}, inplace=True)
newdf.head(10)

,DrinkName,Link,IdDrink
0,'57 Chevy with a White License Plate,https://www.thecocktaildb.com/images/media/dri...,14029
1,1-900-FUK-MEUP,https://www.thecocktaildb.com/images/media/dri...,15395
2,110 in the shade,https://www.thecocktaildb.com/images/media/dri...,15423
3,151 Florida Bushwacker,https://www.thecocktaildb.com/images/media/dri...,14588
4,155 Belmont,https://www.thecocktaildb.com/images/media/dri...,15346
5,24k nightmare,https://www.thecocktaildb.com/images/media/dri...,17060
6,252,https://www.thecocktaildb.com/images/media/dri...,15288
7,3 Wise Men,https://www.thecocktaildb.com/images/media/dri...,13899
8,3-Mile Long Island Iced Tea,https://www.thecocktaildb.com/images/media/dri...,15300
9,410 Gone,https://www.thecocktaildb.com/images/media/dri...,13581

In [401]:
export = newdf.to_csv(r'C:/Users/diegogomez/Documents/CODING/IRONHACK/GITHUB/datamex1019/module-1/web-project/export.csv',index=None,header=True)
print(newdf)

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/diegogomez/Documents/CODING/IRONHACK/GITHUB/datamex1019/module-1/web-project/export.csv'